### ISSUE TITLE
Создать блок Чата (Соединить блок написания сообщения и блок отображения переписки)

### ISSUE THREAD

**Issue by jegius** [J-Lany/daniella-edu#2]
![image](https://github.com/J-Lany/daniella-edu/assets/11362702/d63b2dee-2cdb-4044-a05c-38743ee1a31f)

**Comment by J-Lany** [comment]
Это было объединено в рамках этой задачки https://github.com/J-Lany/daniella-edu/pull/24 

Или нужно создать компонент для:
    <messages-block></messages-block>
    <message-input></message-input>
