### ISSUE TITLE
Добавить на бэк логику создания чата 

### ISSUE THREAD

**Issue by jegius** [J-Lany/daniella-edu#25]
логика будет следующей 
- контроллер принимает id пользователя с которым создается чат (может быть массив)
- в контроллер получает айди сесси для определения текущего пользователя и передает его в чат серис и создает объект чат у которого будет id чата дата создания чата, и массив с айдишниками всех его учатников
- Так же нужно сделть методы контроллера на обновление чата, удаления учатников чата, удаления чата

**Comment by J-Lany** [comment]
> контроллер получает айди сесси для определения текущего пользователя 

Это надо переписать бэк, чтобы по айди  сессии (токену) получать текущего пользователя? Или нужно создать найди сессии (Что это должно быть? Ни разу с таким не сталкивалась :(

**Comment by J-Lany** [comment]
> Так же нужно сделть методы контроллера на обновление чата, удаления учатников чата, удаления чата

А методы контролера создаются отдельными функциями? (например в файле create-chat-controller) Или какая-то другая логика?
