### ISSUE TITLE
Создать компонент поиска по активным перепискам

### ISSUE THREAD

**Issue by jegius** [J-Lany/daniella-edu#6]
Инпут связанный с компонентом отображения активных переписок, пир вводе данных делает запросы на бэк и получает списаок чатов по отправленному тексту

![image](https://github.com/J-Lany/daniella-edu/assets/11362702/b039d73c-bea2-45b4-9e17-23b9ad630e13)

**Comment by J-Lany** [comment]
Инпут создан в рамках https://github.com/J-Lany/daniella-edu/issues/44 но сейчас ищет только пользователей
