### ISSUE TITLE
Разделить компонент карточки переписки и сообщения в блоке переписки

### ISSUE THREAD

**Issue by jegius** [J-Lany/daniella-edu#8]
в нем должнобыть - картинка с последнего поста с чата, сокращенное последнее сообщение, имя и Дата последнего сообщения

пока что делаем на моках

![image](https://github.com/J-Lany/daniella-edu/assets/11362702/9680a739-ad9f-41bf-b075-9e9cea72bc3e)

**Comment by J-Lany** [comment]
Тут, полагаю, будем делать уже не на Моках :)

**Comment by J-Lany** [comment]
сейчас опять оно  не скролится и можно максимум добавить 10 сообщений а дальше уедет компонент отправки и отправить нельзя будет

**Comment by J-Lany** [comment]
имя пользователя сливается с самим сообщениеем

**Comment by J-Lany** [comment]
аватар больно большой

**Comment by J-Lany** [comment]
И прочите баги
